[package]
name = "user-management"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10.2"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
tonic-build = "0.11.0"
prost = "0.12.4"
d = "0.0.1"
tonic-reflection = "0.11.0"
protos = { path = "./gen" }
diesel = { version = "2.1.6", features = ["postgres_backend", "postgres", "uuid"] }
dotenvy = "0.15.7"
uuid = "1.8.0"

[build-dependencies]
tonic-build = "0.11.0"

[workspace]
members = [
    "gen"
]
