name: PR Tests

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: auth_service
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6380:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: make migration && make test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/auth_service
          REDIS_HOSTNAME: localhost:6379
          REDIS_TLS: false
          ACCESS_TOKEN_SECRET: secret
          ACCESS_TOKEN_TTL: 60
          REFRESH_TOKEN_SECRET: secret
          REFRESH_TOKEN_TTL: 86400
          JWT_ISSUER: auth_service
          OTP_SECRET: EMZXDFRGOLH3JBQ4U2JQXSMXDDWD2I5J
          OTP_TTL: 60
          ENABLE_IPV6: false
          PORT: 50051
          METRICS_PORT: 3000